name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Testing all packages that run as lambda services
  test-lambdas:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/dealmore/dealmore-build-images/lambdaci:nodejs12.x
    services:
      s3:
        image: registry.gitlab.com/dealmore/dealmore-build-images:s3-emulator
        env:
          MINIO_ACCESS_KEY: test
          MINIO_SECRET_KEY: testtest

    env:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: testtest
      S3_ENDPOINT=s3:9000

    steps:
      - uses: actions/checkout@v2

      - name: Jest
        run: |
          yarn --frozen-lockfile --cache-folder .yarn
          yarn test

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-test
